### PR TITLE
Blockchain and Computer Vision

### PR DESCRIPTION
**Pull request by chaoticji**

### CODE REVIEW

**Comment by dancju** [comment]
Thank you! But your commits is a little bit messy. It should be two commits if you are trying to add two nanodegrees.

**Comment by chaoticji** [comment]
> Thank you! But your commits is a little bit messy. It should be two commits if you are trying to add two nanodegrees.

Lol. yeah i messed up a little while uploading through UI. Wanted to push from a new account and adding two git accounts on the same system looked confusing to me so chose this path. You can add these -> https://siasky.net/_AqGOwlOdoO7briyo2L3m_5zLscH0k6qa7fw3vnPV4wJ_w

**Comment by dancju** [comment]
@chaoticji Thank you! But why "Product Manager" does not have a version number?

**Comment by chaoticji** [comment]
It is v1.0.0 . I renamed the folder before this repo came into existence so that it is why.

**Pull request closed without merging**
